---
language: python

python: "2.7"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl

install:
  - pip install ansible==1.9.1
  - "printf '[defaults]\\nroles_path = ../' > ansible.cfg"

before_script:
  - echo localhost > inventory
  - ansible-galaxy --role-file requirements.yml

script:
  - ansible-playbook --syntax-check -i inventory test.yml
  - ansible-playbook -i inventory test.yml --connection=local --sudo
  # Taken from https://servercheck.in/blog/testing-ansible-roles-travis-ci-github
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

